; Template End Gcode with Variables
; Generated by VTP Lithophane Generator
; -------------------------
M104 S0 ; Turn off nozzle temp
M140 S0 ; Turn off bed temp
G91 ; Relative positioning
G1 E-{retract_length} F{retract_speed} ; Retract
G90 ; Absolute positioning
G1 Z{z_lift} F{travel_speed} ; Lift nozzle
G28 X Y ; Home X and Y
M84 ; Disable motors

; Print completed
; Duration: {print_time}
; Material used: {filament_used}mm
